MVHS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Inicio.urls')),
    path('adm/', include('administrativo.urls')),
    path('manutencao/', include('manutencao.urls')),
    path('frota/', include('frota.urls')),
    path('epis/', include('epis.urls')),
    path('abastecimento/', include('abastecimento.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administrativo/urls.py
from django.urls import path

from administrativo import views as v

from django.contrib.auth import views as auth_views
app_name = 'administrativo'


urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', v.force_logout, name='logout'),
    path('nao_autorizado/', v.nao_autorizado, name='nao_autorizado'),
    path('', v.adm, name='admin'),
    
    path('formulario_motorista/',
          v.formulario_Motorista.as_view(),
            name='formulario_motorista'),

    path('formulario_ajudante/',
          v.formulario_Ajudante.as_view(),
            name='formulario_ajudante'),

    path('formulario_caminhao/',
          v.formulario_caminhao.as_view(),
            name='formulario_caminhao'),

    path('formulario_cargas/',
          v.formulario_cargas.as_view(),
            name='formulario_cargas'),

    path('fornulario_lista/',
          v.fornulario_lista.as_view(),
            name='fornulario_lista'),

    path('caminhao_lista/',
          v.caminhao_lista.as_view(),
            name='caminhao_lista'),

    path('motorista_lista/',
          v.motorista_lista.as_view(),
            name='motorista_lista'),

    path('ajudante_lista/',
          v.ajudante_lista.as_view(),
            name='ajudante_lista'),

    path('pesquisar_revenda/',
          v.pesquisar_revenda,
            name='pesquisar_revenda'),

    path('pesquisar_td/',
          v.pesquisar_td,
            name='pesquisar_td'),
            
    path('pes_imprimir/',
          v.pes_imprimir,
            name='pes_imprimir'),

    path('reiniciar_tabela_carga',
          v.reiniciar_tabela_carga,
            name='reiniciar_tabela_carga'),

    path('del_itens_tab_carga',
          v.del_itens_tab_carga,
            name='del_itens_tab_carga'),
   
 
]

epis/urls.py
from django.urls import path

from epis import views as v

app_name = 'epis'


urlpatterns = [
    path('', v.epis, name='epis'),

    path('formulario_epis/',
          v.formulario_epis.as_view(),
            name='formulario_epis'),

    path('fomulario_uniformes',
          v.formulario_uniformes.as_view(),    
            name='formulario_uniformes'),

    path('formulario_outros',
          v.formulario_outros.as_view(),    
            name='formulario_outros'),    

    
]

epis/models.py
from django.db import models

# Create your models here.

epis/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from db_mvhs.models import *
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

@login_required# Create your views here.
def epis(request):
    return render(request,'epis.html')



class formulario_epis(CreateView):
    model = epis_base
    fields = '__all__'
    template_name = 'formularios.html'

    def get_success_url(self):
        return reverse_lazy('Inicio:index')
    
class formulario_uniformes(CreateView):
    model = uniformes_base
    fields = '__all__'
    template_name = 'formularios.html'

    def get_success_url(self):
        return reverse_lazy('Inicio:index')
    
class formulario_outros(CreateView):
    model = outros_base
    fields = '__all__'
    template_name = 'formularios.html'

    def get_success_url(self):
        return reverse_lazy('Inicio:index')

epis/templates/epis.html
{% extends "base.html" %}
{%load static%}
{% block css %}

  <style>
    .form-control {
      margin: 16px;
    }
  </style>

{% endblock css %}
{% block content %}


<div class="container-center p-2">
    <nav class="navbar bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">
          <header class="box-texto">
            <h1 class="title">MVHS</h1>
            <span class="descricao">Informações</span>
        </header></a>
      </div>
    </nav>
</div>

<div class='container text-center p-2 rounded-4'>

      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="btn-group-vertical" role="group" aria-label="Vertical button group">
          <div class='flex-container text-center p-2 text-danger-emphasis bg-danger-subtle border border-danger-subtle  rounded-4'>

          <p><a class="button_abastecimento" type="button"href="{% url 'epis:formulario_epis'%}">EPIs</a></p>
          <p><a class="button_abastecimento" type="button"href="{% url 'epis:formulario_uniformes'%}">Uniformes</a></p>
          <p><a class="button_abastecimento" type="button"href="{% url 'epis:formulario_outros'%}">Outros</a></p>
</div></div>
      </nav>
</div>
<div class='flex-container text-center p-2 text-danger-emphasis bg-danger-subtle border border-danger-subtle  rounded-4'>

<div class="container-center p-2">
<nav class="navbar bg-body-tertiary">
  <div class="container-fluid">
    <a class="button_adm" href="/">Retornar</a>
  </div>
  <br><br>
  <br><br>
</nav>
      {% if user.is_authenticated %}
        <div class="container align-center">
          <a href="{% url 'administrativo:logout'%}"class='button_manutencao'>Sair: {{user.username}}</a>
        </div>
      {% endif %}
      </nav>
</div>
</div>
</div>
</div>

{% endblock content %}