MVHS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Inicio.urls')),
    path('adm/', include('administrativo.urls')),
    path('manutencao/', include('manutencao.urls')),
    path('frota/', include('frota.urls')),
    path('epis/', include('epis.urls')),
    path('abastecimento/', include('abastecimento.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administrativo/urls.py
from django.urls import path

from administrativo import views as v

from django.contrib.auth import views as auth_views
app_name = 'administrativo'


urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', v.force_logout, name='logout'),
    path('nao_autorizado/', v.nao_autorizado, name='nao_autorizado'),
    path('', v.adm, name='admin'),
    
    path('formulario_motorista/',
          v.formulario_Motorista.as_view(),
            name='formulario_motorista'),

    path('formulario_ajudante/',
          v.formulario_Ajudante.as_view(),
            name='formulario_ajudante'),

    path('formulario_caminhao/',
          v.formulario_caminhao.as_view(),
            name='formulario_caminhao'),

    path('formulario_cargas/',
          v.formulario_cargas.as_view(),
            name='formulario_cargas'),

    path('fornulario_lista/',
          v.fornulario_lista.as_view(),
            name='fornulario_lista'),

    path('caminhao_lista/',
          v.caminhao_lista.as_view(),
            name='caminhao_lista'),

    path('motorista_lista/',
          v.motorista_lista.as_view(),
            name='motorista_lista'),

    path('ajudante_lista/',
          v.ajudante_lista.as_view(),
            name='ajudante_lista'),

    path('pesquisar_revenda/',
          v.pesquisar_revenda,
            name='pesquisar_revenda'),

    path('pesquisar_td/',
          v.pesquisar_td,
            name='pesquisar_td'),
            
    path('pes_imprimir/',
          v.pes_imprimir,
            name='pes_imprimir'),

    path('reiniciar_tabela_carga',
          v.reiniciar_tabela_carga,
            name='reiniciar_tabela_carga'),

    path('del_itens_tab_carga',
          v.del_itens_tab_carga,
            name='del_itens_tab_carga'),
   
 
]

frota/urls.py
from django.urls import path

from frota import views as v

app_name = 'frota'


urlpatterns = [
    path('', v.frota, name='frota'),

    path('formulario_td/',
          v.formuloario_td.as_view(),
            name='formulario_td'),  

    path('td_list/',
          v.td_list.as_view(),
            name='td_list'),    

    path('formulario_revenda/',
          v.formulario_revenda.as_view(),
            name='formulario_revenda'),

    path('revenda_lista/',
          v.revenda_lista.as_view(),
            name='revenda_lista'),

    path('revenda_OK/',
          v.revenda_ok,
            name='revenda_OK'),
    
    path('formulario_manutencao/',
          v.formulario_manutencao.as_view(),
            name='formulario_manutencao'),

    path('ver_lista_carga/',
          v.ver_lista_carga.as_view(),
            name='ver_lista_carga'),

]

manutencao/urls.py
from django.urls import path

from manutencao import views as v

app_name = 'manutencao'


urlpatterns = [
    path('', v.manutencao, name='manu'),

    
    path('manutencao_lista/',
          v.manutencao_lista.as_view(),
            name='manutencao_lista'),
  
    path('acao_manutencao/',
          v.acao_manutencao.as_view(),
            name='acao_manutencao'),

    path('agendamento_lista/',
          v.agendamento_lista.as_view(),
            name='agendamento_lista'),
     
    
]

frota/models.py
from django.db import models

# Create your models here.

frota/views.py
from django.shortcuts import render
from administrativo import views
from django.views.generic import CreateView,ListView,DateDetailView
from db_mvhs.models import *
from db_mvhs.forms import *
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
# Create your views here.
@login_required
def frota(request):
    return render(request, 'frota.html')

class formuloario_td(CreateView):
    model = tab_td      
    template_name = 'formularios.html'
    form_class = forms_td

class td_list(ListView):
    model = tab_td
    template_name = 'td_list.html'
    paginate_by = 15


class formulario_revenda(CreateView):
    model = Revenda      
    template_name = 'formularios.html'
    form_class = forms_revenda

class revenda_lista(ListView):
    model = Revenda
    template_name = 'lista_revenda.html'
    paginate_by = 5


def revenda_ok(request):
    return render(request, 'revenda_ok.html')

class formulario_manutencao(CreateView):
    model = Manutencao      
    template_name = 'formularios.html'
    form_class = forms_manutencao

class ver_lista_carga(ListView):
    model =Cargas    
    template_name= 'ver_lista_cargas.html'       
    paginate_by=5
    

frota/templates/frota.html
{% extends "base.html" %}
{%load static%}
{% block css %}

  <style>
    .form-control {
      margin: 16px;
    }
  </style>

{% endblock css %}
{% block content %}


<div class="container-center p-2">
    <nav class="navbar bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">
          <header class="box-texto">
            <h1 class="title">MVHS</h1>
            <span class="descricao">Informações</span>
        </header></a>
      </div>
    </nav>
</div>

<div class='container text-center p-2 rounded-4'>

      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="btn-group-vertical" role="group" aria-label="Vertical button group">
          <div class='flex-container text-center p-2 text-danger-emphasis bg-danger-subtle border border-danger-subtle  rounded-4'>

          <p><a class="button_frota" type="button"href="{% url 'frota:ver_lista_carga'%}">Ver Cargas de Hoje</a></p>
          <p><a class="button_frota" type="button"href="{% url 'frota:formulario_td'%}">Adicionar TD</a></p>
          <p><a class="button_frota" type="button"href="{% url 'frota:formulario_revenda'%}">Saida, Retorno e Revenda</a></p> 
          </div><br><br>
          <div class='flex-container text-center p-2 text-danger-emphasis bg-danger-subtle border border-danger-subtle  rounded-4'>         
          <p><a class="button_manutencao" type="button"href="{% url 'frota:formulario_manutencao'%}">Pedido de Manutenção</a></p>
          <p><a class="button_manutencao" type="button"href="{% url 'manutencao:agendamento_lista'%}">Agenda de pedidos</a></p>
          </div>
      
        </div>  
      </nav>
</div>
      <div class='container text-center p-2 rounded-4'>
      <nav class="navbar bg-body-tertiary">
        <div class="container-fluid">
          <a class="button_adm" href="/">Retornar</a>
        </div>
      </nav>
      <nav class="navbar bg-body-tertiary">
      {% if user.is_authenticated %}
      <div class="container align-center">
        <a href="{% url 'administrativo:logout'%}"class='button_manutencao'>Sair: {{user.username}}</a>
      </div>

    {% endif %}
      </nav>
      </div>
</div>
</div>
</div>
{% endblock content %}

frota/templates/lista_revenda.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% load bootstrap %}
{% block css %}
{% endblock css %}

{% block content %}
<nav class="navbar" style="background-color: #e3f2fd;">
  MVHS informações
</nav>
<div class='container text-center p-2 text-primary-emphasis bg-danger-subtle border border-primary-subtle  rounded-3'>


<nav class="navbar bg-body-tertiary">
  <div class="container-fluid">
    <a class="button_adm" href="/">Retornar</a>
  </div>
</nav>

<h1 class='text-center'>Lista de Revendas</h1>
<ul>


  {% for obj in object_list %}

  <tr>
    <div class="card text-bg-secondary mb-3" style="max-width: 22rem;">
      <div class="card-header bg-transparent border-success text-success">
        <h4>{{ obj.link_caminhao}}</h4>
        <h6>TD:  {{ obj.link_td}}</h6>
        <h6>Entrada:  {{ obj.entrada}}</h6>
        <h6>Horario:  {{ obj.horario}}</h6>
    </div>
      <div class="card-body ">
        <table class="table table-success table-striped">
       <tr>
        <th>Ação:</th><td>{{ obj.acao}}</td></tr>
        <th>km:</th><td>{{ obj.km}}</td></tr>
        <th>Cliente:</th><td>{{ obj.cliente}}</td></tr>
        <th>Codigo:</th><td>{{ obj.codigo_cliente}}</td></tr>
        <th>Nota 1:</th><td>{{ obj.nota_1}}</td></tr>
        <th>Nota 2:</th><td>{{ obj.nota_2}}</td></tr>
        <th>P2:</th><td>{{ obj.p2}}</td></tr>
        <th>P5:</th><td>{{ obj.p5}}</td></tr>
        <th>P8:</th><td>{{ obj.p8}}</td></tr>
        <th>P13:</th><td>{{ obj.p13}}</td></tr>
        <th>P20:</th><td>{{ obj.p20}}</td></tr>
        <th>P45:</th><td>{{ obj.p45}}</td></tr>
        <th>link_motorista:</th><td>{{ obj.link_motorista}}</td></tr>
        <th>link_ajudante:</th><td>{{ obj.link_Ajudante}}</td></tr>
        
        </table>
      </div>

    </div>
    

  </tr>
{% empty %}
  <li>Não há itens na tabela!</li>
{% endfor %}
    </tbody>

  </table>
</ul>
{% include "includes/pagination.html" %}
</div>

{% endblock content %}

{% block js %}

{% endblock js %}

frota/templates/revenda_ok.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% load bootstrap %}
{% block css %}

  <style>
    .form-control {
      margin: 10px;
    }
  </style>



{% endblock css %}

{% block content %}
<nav class="navbar" style="background-color: #e3f2fd;">
  <h1>MVHS informações</h1>
  <br><br><br><br>
   <p><a class="button_adm" type='button'href="{% url 'frota:formulario_revenda'%}">Cadastrar nova revenda</a></p>
</nav>
<br>
<div class='container text-center p-2 text-primary-emphasis bg-danger-subtle border border-primary-subtle  rounded-3'>
  <h1 class='text-center'>Revenda cadastrada com sucesso!</h1>
</div>

<nav class="navbar" style="background-color: #e3f2fd;">

   <p><a class="button_adm" type='button'href="/">Retornar ao inicio</a></p>
</nav>
{% endblock content %}

{% block js %}

{% endblock js %}

frota/templates/revenda_pesquisar.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% load bootstrap %}
{% block css %}
{% endblock css %}

{% block content %}
<nav class="navbar" style="background-color: #e3f2fd;">
  MVHS informações
   <p><a class="button_adm" type='button'href="/">Retornar</a></p>
</nav>
<br>
<div class='container text-center p-2 text-primary-emphasis bg-danger-subtle border border-primary-subtle  rounded-3'>
  <form method="GET">
      <div class="container">
        <h6>Data inicial e final</h6>
        <div class="input-group">
          <div class="input-group-prepend">
            <input class="form-control "aria-describedby="basic-addon1" name="d1" type="date" ><br>
          </div>  
          <br>
          <div class="input-group-prepend">
            <input class="form-control " aria-describedby="basic-addon2"name="d2" type="date" ><br>
          </div>
        </div>
          <br>
          <div class="conteiner">
            <button class="button_frota" type="submit">{{acao}}</button>
        </div>
       </div>
      </div>

    </form>

<ul>
  <br>
  <h6>Pesquisa entre as datas:</h6><h6>{{texto}}</h6>
  <br>
  <table class="table table-hover">

  {% for Revenda in object_list %}

  <tr><th scope="col">TD</th><td>{{ Revenda.link_td }}</td></tr>
  <tr><th scope="col">Veiculo</th><td>{{ Revenda.link_caminhao }}</td></tr>
  <tr><th scope="col">Motorista</th><td>{{ Revenda.link_motorista }}</td></tr>
  <tr><th scope="col">Ajudante</th><td>{{ Revenda.link_Ajudante }}</td></tr>
  <tr><th scope="col">km</th><td>{{ Revenda.km }}</td></tr>
  <tr><th scope="col">Cliente</th><td>{{ Revenda.cliente }}</td></tr>
  <tr><th scope="col">Codigo Cliente</th><td>{{ Revenda.codigo_cliente }}</td></tr>
  <tr><th scope="col">Nf 1</th><td>{{ Revenda.nota_1 }}</td></tr>
  <tr><th scope="col">Nf 2</th><td>{{ Revenda.nota_2 }}</td></tr>
  <tr><th scope="col">p2</th><td>{{ Revenda.p2 }}</td></tr>
  <tr><th scope="col">p5</th><td>{{ Revenda.p5 }}</td></tr>
  <tr><th scope="col">p8</th><td>{{ Revenda.p8 }}</td></tr>
  <tr><th scope="col">p13</th><td>{{ Revenda.p13 }}</td></tr>
  <tr><th scope="col">p20</th><td>{{ Revenda.p20 }}</td></tr>
  <tr><th scope="col">p45</th><td>{{ Revenda.p45 }}</td></tr>
  <tr><th scope="col">Data</th><td>{{ Revenda.entrada }}</td></tr>
  <tr><th scope="col">Horario</th><td>{{Revenda.horario}}</td></tr>
  <tr><th scope="col">OBS</th><td>{{ Revenda.OBS }}</td></tr>
  <tr><th scope="col"></th><td>.</td></tr>

{% empty %}
  <li>Não há itens na tabela!</li>
{% endfor %}
    </tbody>
  </table>
  <br>
</ul>
{% include "includes/pagination.html" %}
</div>
{% endblock content %}

{% block js %}

{% endblock js %}

frota/templates/revenda_view.html
{{objects}}

{{context}}

frota/templates/td_list.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% load bootstrap %}
{% block css %}
{% endblock css %}

{% block content %}
<nav class="navbar" style="background-color: #e3f2fd;">
  MVHS informações
</nav>
<div class='container text-center p-2 text-primary-emphasis bg-danger-subtle border border-primary-subtle  rounded-3'>


<nav class="navbar bg-body-tertiary">
  <div class="container-fluid">
    <a class="button_adm" href="/">Retornar</a>
  </div>
</nav>

<h1 class='text-center'>Lista de TDs</h1>
<ul>


  {% for obj in object_list %}

  <tr>
    <div class="card text-bg-secondary mb-3" style="max-width: 22rem;">
      <div class="card-header bg-transparent border-success text-success"><h6>{{ obj.saida_base}}</h6></div>
      <div class="card-body ">
        <table class="table table-success table-striped">
       <tr>
        <th>TDs:</th><td>{{ obj.td}}</td></tr>
        <th>Reponsavel:</th><td>{{ obj.link_reponsavel}}</td></tr>
        <th>Placa:</th><td>{{ obj.link_placa}}</td></tr>
        </table>
      </div>
      
    </div>
    

  </tr>
{% empty %}
  <li>Não há itens na tabela!</li>
{% endfor %}
    </tbody>

  </table>
</ul>
{% include "includes/pagination.html" %}
</div>

{% endblock content %}

{% block js %}

{% endblock js %}

frota/templates/ver_lista_cargas.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% load bootstrap %}
{% block css %}
{% endblock css %}

{% block content %}
<nav class="navbar" style="background-color: #e3f2fd;">
  <h1>MVHS informações</h1>
</nav>
<div class='container text-center p-2 text-primary-emphasis bg-danger-subtle border border-primary-subtle  rounded-3'>


<nav class="navbar bg-body-tertiary">

  <br>
  <br>
  <br>
  <br>
  <div class="container-fluid">
    <a class="button_adm" href="/">Retornar</a>
  </div>
</nav>

<h1 class='text-center'>Lista de Cargas</h1>


  {% for Cargas in object_list %}

  <tr>
    <div class="card text-bg-secondary mb-3" style="max-width: 22rem;">
      <div class="card-header bg-transparent border-success text-success"><h4>{{ Cargas.Carga_Placa}}</h4></div>
      <div class="card-body ">
        <table class="table table-success table-striped">
       <tr>
        <th>p2:</th><td>{{ Cargas.p2}}</td> 
        <th>p5:</th><td>{{ Cargas.p5}}</td>
        <th>p8:</th><td>{{ Cargas.p8}}</td></tr>
        <tr>
        <th>p13:</th><td>{{ Cargas.p13}}</td> 
        <th>p20:</th><td>{{ Cargas.p20}}</td>
        <th>p45:</th><td>{{ Cargas.p45}}</td></tr>
        

        <p>Cor :{{ Cargas.cor}}</p>
        </table>
      </div>
      <div class="card-footer bg-transparent border-success">{{ Cargas.data}}</div>
    </div>
    

  </tr>
{% empty %}
  <li>Não há itens na tabela!</li>
{% endfor %}
    </tbody>

  </table>
</ul>
{% include "includes/pagination.html" %}
</div>

{% endblock content %}

{% block js %}

{% endblock js %}