MVHS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Inicio.urls')),
    path('adm/', include('administrativo.urls')),
    path('manutencao/', include('manutencao.urls')),
    path('frota/', include('frota.urls')),
    path('epis/', include('epis.urls')),
    path('abastecimento/', include('abastecimento.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administrativo/urls.py
from django.urls import path

from administrativo import views as v

from django.contrib.auth import views as auth_views
app_name = 'administrativo'


urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', v.force_logout, name='logout'),
    path('nao_autorizado/', v.nao_autorizado, name='nao_autorizado'),
    path('', v.adm, name='admin'),
    
    path('formulario_motorista/',
          v.formulario_Motorista.as_view(),
            name='formulario_motorista'),

    path('formulario_ajudante/',
          v.formulario_Ajudante.as_view(),
            name='formulario_ajudante'),

    path('formulario_caminhao/',
          v.formulario_caminhao.as_view(),
            name='formulario_caminhao'),

    path('formulario_cargas/',
          v.formulario_cargas.as_view(),
            name='formulario_cargas'),

    path('fornulario_lista/',
          v.fornulario_lista.as_view(),
            name='fornulario_lista'),

    path('caminhao_lista/',
          v.caminhao_lista.as_view(),
            name='caminhao_lista'),

    path('motorista_lista/',
          v.motorista_lista.as_view(),
            name='motorista_lista'),

    path('ajudante_lista/',
          v.ajudante_lista.as_view(),
            name='ajudante_lista'),

    path('pesquisar_revenda/',
          v.pesquisar_revenda,
            name='pesquisar_revenda'),

    path('pesquisar_td/',
          v.pesquisar_td,
            name='pesquisar_td'),
            
    path('pes_imprimir/',
          v.pes_imprimir,
            name='pes_imprimir'),

    path('reiniciar_tabela_carga',
          v.reiniciar_tabela_carga,
            name='reiniciar_tabela_carga'),

    path('del_itens_tab_carga',
          v.del_itens_tab_carga,
            name='del_itens_tab_carga'),
   
 
]

manutencao/urls.py
from django.urls import path

from manutencao import views as v

app_name = 'manutencao'


urlpatterns = [
    path('', v.manutencao, name='manu'),

    
    path('manutencao_lista/',
          v.manutencao_lista.as_view(),
            name='manutencao_lista'),
  
    path('acao_manutencao/',
          v.acao_manutencao.as_view(),
            name='acao_manutencao'),

    path('agendamento_lista/',
          v.agendamento_lista.as_view(),
            name='agendamento_lista'),
     
    
]

manutencao/models.py
from django.db import models

# Create your models here.

manutencao/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView
from db_mvhs.models import *
from manutencao.models import *
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
# Create your views here.
@login_required
def manutencao(request):
    return render(request, 'manu.html')


class manutencao_lista(ListView):
    model = Manutencao       
    template_name = 'manutencao_lista.html'     

    def get_queryset(self):
        return Manutencao.objects.all().order_by('-data')   
    
class acao_manutencao(CreateView):
    model = Manutencao_Resposta
    fields = '__all__'
    template_name = 'formularios.html'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        return super().form_invalid(form)   
    
class agendamento_lista(ListView):
    model = Manutencao_Resposta
    template_name = 'agendamento_lista.html'

    def get_queryset(self):
        return Manutencao_Resposta.objects.all().order_by('-data')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['agendamento'] = Manutencao_Resposta.objects.all().order_by('-data')
        return context
    

    

manutencao/templates/agendamento_lista.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% load bootstrap %}
{% block css %}

  <style>
    .form-control {
      margin: 16px;
    }
  </style>

<link rel="stylesheet" href="{% static 'css/estilo2.css' %}">

{% endblock css %}

{% block content %}
<nav class="navbar" style="background-color: #e3f2fd;">
  MVHS informações
</nav>
<div class='container text-center p-2 text-primary-emphasis bg-danger-subtle border border-primary-subtle  rounded-3'>
<br>
<nav class="navbar bg-body-tertiary">
  <div class="container-fluid">
    <a class="button_adm" href="/">Retornar</a>
  </div>
</nav>

<h1 class='text-center'>Dados dos agendamentos</h1>
<ul>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Responsavel</th>
        <th scope="col">Agendado para</th>
        <th scope="col">Data da resposta</th>
        <th scope="col">Hora</th>
        <th scope="col">Placa</th>


      </tr>
    </thead>
    <tbody>

  {% for Manutencao in object_list %}

  <tr>

    <td>{{ Manutencao.responsavel}}</td>
    <td>{{ Manutencao.Agendado}}</td>
    <td>{{ Manutencao.data}}</td>
    <td>{{ Manutencao.horario}}</td>
     <td>{{ Manutencao.link_agendado }}</td>
     <tr>
      <th scope="col">Descrição</th><td colspan="5">{{ Manutencao.descricao}}</td>
     </tr><br>
  </tr>
{% empty %}
  <li>Não há itens na tabela!</li>
{% endfor %}
    </tbody>
  </table>
</ul>
{% include "includes/pagination.html" %}
</div>
{% endblock content %}

{% block js %}

{% endblock js %}

manutencao/templates/manu.html
{% extends "base.html" %}
{%load static%}
{% block css %}

  <style>
    .form-control {
      margin: 16px;
    }
  </style>

{% endblock css %}
{% block content %}


<div class="container-center p-2">
    <nav class="navbar bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">
          <header class="box-texto">
            <h1 class="title">MVHS</h1>
            <span class="descricao">Informações</span>
        </header></a>
      </div>
    </nav>
</div>

<div class='flex-container text-center p-2 rounded-4'>
  <div>
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="btn-group-vertical" role="group" aria-label="Vertical button group">

          <div class='flex-container text-center p-2 text-primary-emphasis bg-danger-subtle border border-primary-subtle  rounded-4'>
              <div>
              <p><a class="button_manutencao" type="button"href="{% url 'manutencao:agendamento_lista'%}">Manutenção agendada</a></p>
              <a class="navbar-brand" href="/"><h4>Controle de Manutenção</h4></a>
              <p><a class="button_manutencao" type="button"href="{% url 'manutencao:manutencao_lista'%}">lista de pedidos</a></p>
              <p><a class="button_manutencao" type="button"href="{% url 'manutencao:acao_manutencao'%}">Ações</a></p>
          </div>
          </div>
        </div>
      </nav>

      <nav class="navbar bg-body-tertiary">
        <div class="container-fluid">
          <a class="button_adm" href="/">Retornar</a>
        </div>
      </nav>
        <div class='container text-center p-2 rounded-4'>
      {% if user.is_authenticated %}
        <div class="container align-center">
          <a href="{% url 'administrativo:logout'%}"class='button_manutencao'>Sair: {{user.username}}</a>
        </div>
      {% endif %}
      </nav>
  </div>
  </div>
</div>

{% endblock content %}

manutencao/templates/manutencao_lista.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% load bootstrap %}
{% block css %}

  <style>
    .form-control {
      margin: 16px;
    }
  </style>

<link rel="stylesheet" href="{% static 'css/estilo2.css' %}">

{% endblock css %}

{% block content %}
<nav class="navbar" style="background-color: #e3f2fd;">
  MVHS informações
</nav>
<div class='container text-center p-2 text-primary-emphasis bg-danger-subtle border border-primary-subtle  rounded-3'>
<br>
<nav class="navbar bg-body-tertiary">
  <div class="container-fluid">
    <a class="button_adm" href="/">Retornar</a>
  </div>
</nav>

<h1 class='text-center'>Pedidos de manutenção</h1>
<ul>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Numero de registro</th>
        <th scope="col">Responsavel</th>
        <th scope="col">data</th>
        <th scope="col">Hora</th>
        <th scope="col">Placa</th>


      </tr>
    </thead>
    <tbody>

  {% for Manutencao in object_list %}

  <tr>
    <td>{{ Manutencao.id}}</td>
    <td>{{ Manutencao.responsavel}}</td>
    <td>{{ Manutencao.data}}</td>
    <td>{{ Manutencao.horario}}</td>
     <td>{{ Manutencao.link_descricao }}</td>
     <tr>
      <th scope="col">Descrição</th><td colspan="5">{{ Manutencao.descricao}}</td>
     </tr><br>
  </tr>
{% empty %}
  <li>Não há itens na tabela!</li>
{% endfor %}
    </tbody>
  </table>
</ul>
{% include "includes/pagination.html" %}
</div>
{% endblock content %}

{% block js %}

{% endblock js %}