MVHS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Inicio.urls')),
    path('adm/', include('administrativo.urls')),
    path('manutencao/', include('manutencao.urls')),
    path('frota/', include('frota.urls')),
    path('epis/', include('epis.urls')),
    path('abastecimento/', include('abastecimento.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

abastecimento/urls.py
from django.urls import path

from abastecimento import views as v

app_name = 'abastecimento'


urlpatterns = [
    path('', v.abastecimento, name='abastecimento'),

    path('formulario_Abastecimento/',
          v.formulario_Abastecimento.as_view(),
            name='formulario_Abastecimento'),

    path('Abastecimento_lista/',
          v.Abastecimento_lista.as_view(),
            name='Abastecimento_lista'),

    path('abastecimento_imprimir/',
          v.abastecimento_imprimir,
            name='abastecimento_imprimir'),

]

administrativo/urls.py
from django.urls import path

from administrativo import views as v

from django.contrib.auth import views as auth_views
app_name = 'administrativo'


urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', v.force_logout, name='logout'),
    path('nao_autorizado/', v.nao_autorizado, name='nao_autorizado'),
    path('', v.adm, name='admin'),
    
    path('formulario_motorista/',
          v.formulario_Motorista.as_view(),
            name='formulario_motorista'),

    path('formulario_ajudante/',
          v.formulario_Ajudante.as_view(),
            name='formulario_ajudante'),

    path('formulario_caminhao/',
          v.formulario_caminhao.as_view(),
            name='formulario_caminhao'),

    path('formulario_cargas/',
          v.formulario_cargas.as_view(),
            name='formulario_cargas'),

    path('fornulario_lista/',
          v.fornulario_lista.as_view(),
            name='fornulario_lista'),

    path('caminhao_lista/',
          v.caminhao_lista.as_view(),
            name='caminhao_lista'),

    path('motorista_lista/',
          v.motorista_lista.as_view(),
            name='motorista_lista'),

    path('ajudante_lista/',
          v.ajudante_lista.as_view(),
            name='ajudante_lista'),

    path('pesquisar_revenda/',
          v.pesquisar_revenda,
            name='pesquisar_revenda'),

    path('pesquisar_td/',
          v.pesquisar_td,
            name='pesquisar_td'),
            
    path('pes_imprimir/',
          v.pes_imprimir,
            name='pes_imprimir'),

    path('reiniciar_tabela_carga',
          v.reiniciar_tabela_carga,
            name='reiniciar_tabela_carga'),

    path('del_itens_tab_carga',
          v.del_itens_tab_carga,
            name='del_itens_tab_carga'),
   
 
]

frota/urls.py
from django.urls import path

from frota import views as v

app_name = 'frota'


urlpatterns = [
    path('', v.frota, name='frota'),

    path('formulario_td/',
          v.formuloario_td.as_view(),
            name='formulario_td'),  

    path('td_list/',
          v.td_list.as_view(),
            name='td_list'),    

    path('formulario_revenda/',
          v.formulario_revenda.as_view(),
            name='formulario_revenda'),

    path('revenda_lista/',
          v.revenda_lista.as_view(),
            name='revenda_lista'),

    path('revenda_OK/',
          v.revenda_ok,
            name='revenda_OK'),
    
    path('formulario_manutencao/',
          v.formulario_manutencao.as_view(),
            name='formulario_manutencao'),

    path('ver_lista_carga/',
          v.ver_lista_carga.as_view(),
            name='ver_lista_carga'),

]

administrativo/models.py
from django.db import models

# Create your models here.

administrativo/views.py
import statistics
import csv
from django.http import HttpResponse
from django.shortcuts import render,redirect
from db_mvhs.models import *
from db_mvhs.forms import *
from django.views.generic import  ListView,CreateView
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout

# Create your views here.
def force_logout(request):
    logout(request)
    context='<h1>Voce saiu do sistema! |---MVHS Informações---|</h1><p><a href="/"type="button" class="button_adm"><h1>Inicio</h1></a></p>'
    return HttpResponse(context)

def nao_autorizado(request):
    logout(request)
    context='<h1>Não foi autorizado! |---MVHS Informações---|</h1><p><a href="/"type="button" class="button_adm"><h1>Inicio</h1></a></p>'
    return HttpResponse(context)

@login_required
def adm(request):
    if request.user.is_superuser:
        return render(request, 'adm.html')
    else:
        return nao_autorizado(request)
    #return render(request, 'adm.html')



class formulario_caminhao(CreateView):
        model =Caminhao
        template_name= 'formularios.html'
        form_class=forms_caminhao
        def is_valid(self):
            valid = super(formulario_caminhao, self).is_valid()
            if not valid:
                return False
            return True
        
        def form_valid(self, form):
            form.save()
            return super(formulario_caminhao, self).form_valid(form)
        
        def form_invalid(self, form):
            return super().form_invalid(form)
    
class formulario_Motorista(CreateView):
    model =Motorista
    template_name= 'formularios.html'
    form_class=forms_Motorista

class formulario_Ajudante(CreateView):
    model =Ajudante
    template_name= 'formularios.html'
    form_class=forms_Ajudante

class formulario_cargas(CreateView):
    model =Cargas
    template_name= 'formularios.html'
    form_class=forms_Cargas

    def get_context_data(self,*args, **kwargs):
        context = super(formulario_cargas,self).get_context_data(*args,**kwargs)
        request=self.request
        if request.user.is_superuser:
            return context
        else:
            reverse_lazy('administrativo:nao_autorizado')
    
    def is_valid(self):
        valid = super(formulario_cargas, self).is_valid()
        if not valid:
            return False
        return True
    def form_valid(self, form):
        form.save()
        return super(formulario_cargas, self).form_valid(form)
    
    def form_invalid(self, form):
        return super().form_invalid(form)       
    

        
class fornulario_lista(ListView):
    model =Cargas    
    template_name= 'lista_cargas.html'       
    paginate_by=5

class caminhao_lista(ListView):
     model =Caminhao    
     template_name= 'lista_caminhao.html'
     paginate_by=10

class motorista_lista(ListView):
     model =Motorista    
     template_name= 'lista_motorista.html'
     paginate_by=10

class ajudante_lista(ListView):
     model =Ajudante    
     template_name= 'lista_ajudante.html'
     paginate_by=10

    
def pesquisar_revenda(request):
    object_list=Revenda.objects.all()
    d1=request.GET.get('d1')
    d2=request.GET.get('d2')
    acao='Pesquisar entre datas'

    texto= d1, d2
    if d1 and d2:
        object_list=object_list.filter(entrada__range=[d1,d2])

   
    
    context = {
        'acao':acao,
        'texto':texto,
        'object_list':object_list

    }
    return render(request, 'revenda_pesquisar.html',context)

#soma com tara de cada caminhão por placa
def soma(object_list,tara):
    sp2=0
    sp5=0
    sp8=0
    sp13=0
    sp20=0
    sp45=0
    skm=0
    km_retorno=0
    km_saida=0

    obj=object_list.all()
    contador=object_list.count()

    for obj in obj:
        skm=skm+obj.km
        acao=obj.acao
        sp2=sp2+obj.p2
        sp5=sp5+obj.p5
        sp8=sp8+obj.p8
        sp13=sp13+obj.p13
        sp20=sp20+obj.p20
        sp45=sp45+obj.p45
        sobj=(((sp2*5)+(sp5*12)+(sp8*16)+(sp13*28)+(sp20*60)+(sp45*90)))
        if acao == 'SAIDA' or acao == 'RETORNO':
            contador=contador-1
        if acao == 'SAIDA':
            km_saida=obj.km
        if acao == 'RETORNO':
            km_retorno=obj.km

    cont=sobj/contador
    csp2=sp2/contador
    csp5=sp5/contador
    csp8=sp8/contador
    csp13=sp13/contador
    csp20=sp20/contador
    csp45=sp45/contador

    cskm= skm
    mediacskm= km_retorno - km_saida
    soma_tara= tara*contador
    mediana=[sp2,sp5,sp8,sp13,sp20,sp45]
    calc_mediana=statistics.median(mediana)
    calc_mediana_baixa=statistics.median_low(mediana)
    calc_mediana_alta=statistics.median_high(mediana)
    calc_media_aritimetica=statistics.mean(mediana)
    calc_media_Harmonica = statistics.harmonic_mean(mediana)


    context = {
        'sp2'  :sp2,'sp5':sp5,'sp8':sp8,'sp13':sp13,
        'sp20' :sp20,'sp45':sp45,'sobj' :sobj,'cont':cont,
        'csp2' :csp2,'csp5':csp5,'csp8':csp8,
        'csp13':csp13,'csp20':csp20,'csp45':csp45,
        'mediacskm':mediacskm,'contador':contador,'soma_tara':soma_tara,
        'calc_mediana':calc_mediana,'calc_mediana_baixa':calc_mediana_baixa,
        'calc_mediana_alta':calc_mediana_alta,'cskm':cskm,
        'calc_media_aritimetica':calc_media_aritimetica,
        'calc_media_Harmonica':calc_media_Harmonica,

    }

    return context
#soma para a pesquisa td e data
def soma_restrita_sem_tara(object_list):

    sp2=0
    sp5=0
    sp8=0
    sp13=0
    sp20=0
    sp45=0
    skm=0
    cskm=0

    obj=object_list.all()
    contador=object_list.count()

    for obj in obj:
        skm=skm+obj.km
        sp2=sp2+obj.p2
        sp5=sp5+obj.p5
        sp8=sp8+obj.p8
        sp13=sp13+obj.p13
        sp20=sp20+obj.p20
        sp45=sp45+obj.p45
        acao=obj.acao
        sobj=(((sp2*5)+(sp5*12)+(sp8*16)+(sp13*28)+(sp20*60)+(sp45*90)))
        if acao == 'SAIDA' or acao == 'RETORNO':
            contador=contador-1
        if acao == 'SAIDA':
            km_saida=obj.km
        if acao == 'RETORNO':
            km_retorno=obj.km

    mediacskm= km_retorno - km_saida

    cont=sobj/contador
    csp2=sp2/contador
    csp5=sp5/contador
    csp8=sp8/contador
    csp13=sp13/contador
    csp20=sp20/contador
    csp45=sp45/contador

    t_obj= Caminhao.objects.all()

    for t_obj in t_obj:
        cskm= cskm + t_obj.tara


    mediana=[sp2,sp5,sp8,sp13,sp20,sp45]
    calc_mediana=statistics.median(mediana)
    calc_mediana_baixa=statistics.median_low(mediana)
    calc_mediana_alta=statistics.median_high(mediana)
    calc_media_aritimetica=statistics.mean(mediana)
    calc_media_Harmonica = statistics.harmonic_mean(mediana)


    context = {
        'sp2':sp2,'sp5':sp5,'sp8':sp8,'sp13':sp13,
        'sp20':sp20,'sp45':sp45,'sobj' :sobj ,
        'cont':cont,'csp2':csp2,
        'csp5':csp5,'csp8':csp8,'csp13':csp13,
        'csp20':csp20,'csp45':csp45,'cskm':cskm,
        'mediacskm':mediacskm,'contador':contador,
        'calc_mediana':calc_mediana,'calc_mediana_baixa':calc_mediana_baixa,
        'calc_mediana_alta':calc_mediana_alta,'soma_tara':cskm,
        'calc_media_aritimetica':calc_media_aritimetica,
        'calc_media_Harmonica':calc_media_Harmonica,

    }

    return context

#pesquisar
def pesquisar_td(request):
    q=''
    #pesquisa por td
    if 'qtd'in request.GET:
        q=request.GET['qtd']
        if q != '':
            tab_tds=tab_td.objects.all()
            A=tab_tds.filter(td__exact=q)
            if A :
                A=tab_tds.get(td__exact=q)
            else:
                return render(request, 'pesquisar_td.html')
                #pega o id da linha consultada
            B=A.id

            object_list = Revenda.objects.filter(link_td__exact=B)
            soma_context=soma_restrita_sem_tara(object_list)
            context = {
                    'soma_context':soma_context,
                    'object_list' :object_list
                    }
            return render(request, 'pesquisar_td.html',context)
        else:
            return render(request, 'pesquisar_td.html')

    else:
        #pesquisa por placa
        if 'qp'in request.GET:
            qp=request.GET['qp']
            if qp!='':
                tab_caminhao=Caminhao.objects.all()
                A=tab_caminhao.filter(placa_veiculo__icontains=qp)
                if A :
                    A=tab_caminhao.get(placa_veiculo__icontains=qp)
                else:
                    return render(request, 'pesquisar_td.html')
                #pega o id da linha consultada
                B=A.id
                tara=A.tara
                #pesquisa a tabela Revenda atravez do valor id (B)
                object_list = Revenda.objects.filter(link_caminhao__exact=int(B))


                soma_context=soma(object_list,tara)
                context = {
                    'soma_context':soma_context,
                    'object_list' :object_list}
                return render(request, 'pesquisar_td.html',context)
            else:
                return render(request, 'pesquisar_td.html')
        else:
            if 'qd'in request.GET:
                qd=request.GET['qd']
                if qd!='':
                    object_list=Revenda.objects.filter(entrada__contains=qd)
                    if object_list:
                        soma_context=soma_restrita_sem_tara(object_list)
                    else:
                        return render(request, 'pesquisar_td.html')

                    context = {
                    'soma_context':soma_context,
                    'object_list' :object_list}
                    return render(request, 'pesquisar_td.html',context)
                else:
                    return render(request, 'pesquisar_td.html')

    lista_placa=Caminhao.objects.all()
    
    context_placa={
        'lista_placa':lista_placa
    }

    return render(request, 'pesquisar_td.html',context_placa)


def pes_imprimir(request):
    object_list=Revenda.objects.all()

administrativo/templates/adm.html
{% extends "base.html" %}
{%load static%}
{% block css %}

  <style>
    .form-control {
      margin: 16px;
    }
  </style>

{% endblock css %}
{% block content %}



    <nav class="navbar bg-body-tertiary align-center ">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">
          <header class="box-texto">
            <h1 class="title">MVHS</h1>
            <span class="descricao">Informações</span>
        </header></a>
      </div>
    </nav>


<div class='container text-center p-2 rounded-4'>

      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="btn-group-vertical" role="group" aria-label="Vertical button group">

          <div class='flex-container text-center p-2 text-danger-emphasis bg-danger-subtle border border-danger-subtle  rounded-4'>
          <a class="navbar-brand" type="button"href="/"><h4>Cargas </h1></a>
          <p><a class="button_cargas" href="{% url 'administrativo:reiniciar_tabela_carga' %}">Reinicie a tabela para um novo Dia</a></p>
          <p><a class="button_cargas" type="button"href="{% url 'administrativo:formulario_cargas' %}">Cargas de Hoje</a></p>
          </div><br><br>

          <div class='flex-container text-center p-2 text-danger-emphasis bg-danger-subtle border border-danger-subtle  rounded-4'>

          <a class="navbar-brand" type="button"href="/"><h4> Administrativo </h1></a>
          <p><a class="button_adm" type="button"href="{% url 'administrativo:formulario_caminhao' %}">Cadastro de caminhões</a></p>
          <p><a class="button_adm" type="button"href="{% url 'administrativo:formulario_motorista' %}">Cadastro de motorista</a></p>
          <p><a class="button_adm" type="button"href="{% url 'administrativo:formulario_ajudante' %}">Cadastro de Ajudante</a></p>
          </div><br><br>

          <div class='flex-container text-center p-2 text-danger-emphasis bg-danger-subtle border border-danger-subtle  rounded-4'>
          <a class="navbar-brand" type="button"href="/"><h4> Pesquisas </h1></a>
          <p><a href="{% url 'administrativo:pesquisar_revenda' %}"type="button" class="button_adm">pesquisa entre datas</a></p>         
          <p><a class="button_adm" type="button"href="{% url 'administrativo:pesquisar_td' %}">Resultados</a></p>
          <p><a href="{% url 'administrativo:pes_imprimir' %}"type="button" class="button_adm">Revendas imprimir</a></p>
          <p><a href="{% url 'abastecimento:abastecimento_imprimir' %}"type="button" class="button_adm">Abastecimento imprimir</a></p>
          </div><br><br>
          
          <div class='flex-container text-center p-2 text-danger-emphasis bg-danger-subtle border border-danger-subtle  rounded-4'>
          <a class="navbar-brand" type="button"href="/"><h4> Listas </h1></a>
          <p><a href="{% url 'administrativo:caminhao_lista' %}"type="button" class="button_adm">Veiculo lista</a></p>
          <p><a href="{% url 'administrativo:motorista_lista' %}"type="button" class="button_adm">Motorista lista</a></p>
          <p><a href="{% url 'administrativo:ajudante_lista' %}"type="button" class="button_adm">Ajudante lista</a></p>
          <p><a href="{% url 'frota:td_list' %}"type="button" class="button_adm">TD lista</a></p>
          <p><a href="{% url 'frota:revenda_lista' %}"type="button" class="button_adm">Revenda lista</a></p>

          </div>
  
    </nav>
  </div>
</div>

<br>
      <nav class="navbar bg-body-tertiary">
        <div class="container-fluid">
          <a class="button_adm" href="/">Retornar</a>
        </div>
      </nav>
<br>      
      {% if user.is_authenticated %}
      <nav class="navbar bg-body-tertiary">
        <div class="container-fluid">
          <a href='logout'class='button_manutencao'>Sair: {{user.username}}</a>
        </div><br>
      </nav>
      {% endif %}
{% endblock content %}

administrativo/templates/formularios.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% load bootstrap %}

{% block css %}

  <style>
    .form-control {
      margin: 10px;
    }
  </style>



{% endblock css %}

{% block content %}
{% if user.is_authenticated %}
<div class="container">
 <h1>MVHS informações</h1>
      <form method="POST" novalidate>
        {% csrf_token %}
        <legend style="border-bottom: 1px solid #e5e5e5;">{{title}}</legend>

        <div class="row">
          <div class="col-sm-6">
            {% for field in form.visible_fields %}
              <div class="form-group{% if field.errors %} has-error {% endif%}">
                <label for="{{ field.id_for_label }}">
                  {% if field.field.required %}
                    <span class="required">{{ field.label }} </span>
                  {% else %}
                    {{ field.label }}
                  {% endif %}
                </label>
                {% render_field field class="form-control" %}
                {% for error in field.errors %}
                  <span class="text-muted">{{ error }}</span>
                {% endfor %}
              </div>
            {% endfor %}
            {{ formset.management_form }}
          </div>
        </div>
          <div class="row float-center  p-2 text-primary-emphasis bg-danger-subtle border border-primary-subtle  rounded-3">
          <div class="col-sm-6" style="margin-top: 10px;">
            <div class="form-inline buttons">
              <button class="button_frota" value="Save">
                <i class="fa fa-floppy-o"></i>
                Salvar
              </button><br><br><br><br>
              <a href="/" class="button_adm">
                <i class="fa fa-sign-in"></i>
                Retornar ao inicio
              </a>
            </div>
          </div>
        </div>

      </form>
    </div>
  </div>
</div>

{% endif %}
{% endblock content %}

{% block js %}

{% endblock js %}

administrativo/templates/info.html
{% extends "base.html" %}
{%load static%}
{% block css %}

  <style>
    .form-control {
      margin: 16px;
    }
  </style>

{% endblock css %}
{% block content %}
<div class='container text-center p-2 text-primary-emphasis bg-danger-subtle border border-primary-subtle  rounded-4'>
  <div class="card">
    <div class="card-header">
      MVHS informações
    </div>
    <div class="card-body">

  <h4>Reinicie a tabela para o uso de hoje,  </h4>
  <h4>isso mantem a tabela, com os registros somente no dia atual.  </h4>
  <br>
  <h4>Caso não deseje reiniciar a tabela os registros serão ordenados por data, horas e minutos.  </h4>
  <form action="" method="GET">
  <p><a class="button_cargas" name='reiniciar'type="button"href="{% url 'administrativo:del_itens_tab_carga'%}">Reiniciar a tabela </a></p>
  </form>
  <h4>{{texto}}</h4>
</div>
</div>

</div>
<div class='container text-center p-2 text-primary-emphasis bg-danger-subtle border border-primary-subtle  rounded-4'>
    <p><a class="button_adm" type="button"href="{% url 'administrativo:formulario_cargas' %}">Cargas de Hoje</a></p>

    <nav class="navbar bg-body-tertiary">
      <div class="container-fluid">
        <a class="button_adm" href="/">Retornar</a>
      </div>
    </nav>
</div>
{% endblock content %}

administrativo/templates/lista_ajudante.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% load bootstrap %}
{% block css %}
{% endblock css %}

{% block content %}
<nav class="navbar" style="background-color: #e3f2fd;">
  MVHS informações
</nav>
<div class='container text-center p-2 text-primary-emphasis bg-danger-subtle border border-primary-subtle  rounded-3'>


<nav class="navbar bg-body-tertiary">
  <div class="container-fluid">
    <a class="button_adm" href="/">Retornar</a>
  </div>
</nav>

<h1 class='text-center'>Lista de Ajudantes</h1>
<ul>


  {% for obj in object_list %}

  <tr>
    <div class="card text-bg-secondary mb-3" style="max-width: 22rem;">
      <div class="card-header bg-transparent border-success text-success"><h4>{{ obj.ajudante}}</h4></div>
      <div class="card-body ">
        <table class="table table-success table-striped">
       <tr>
        <th>data:</th><td>{{ obj.data}}</td></tr>
        
        
        </table>
      </div>
      
    </div>
    

  </tr>
{% empty %}
  <li>Não há itens na tabela!</li>
{% endfor %}
    </tbody>

  </table>
</ul>
{% include "includes/pagination.html" %}
</div>

{% endblock content %}

{% block js %}

{% endblock js %}

administrativo/templates/lista_caminhao.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% load bootstrap %}
{% block css %}
{% endblock css %}

{% block content %}
<nav class="navbar" style="background-color: #e3f2fd;">
  MVHS informações
</nav>
<div class='container text-center p-2 text-primary-emphasis bg-danger-subtle border border-primary-subtle  rounded-3'>


<nav class="navbar bg-body-tertiary">
  <div class="container-fluid">
    <a class="button_adm" href="/">Retornar</a>
  </div>
</nav>

<h1 class='text-center'>Lista de Veiculos</h1>
<ul>


  {% for obj in object_list %}

  <tr>
    <div class="card text-bg-secondary mb-3" style="max-width: 22rem;">
      <div class="card-header bg-transparent border-success text-success"><h4>{{ obj.Carga_Placa}}</h4></div>
      <div class="card-body ">
        <table class="table table-success table-striped">
       <tr>
        <th>Veiculo:</th><td>{{ obj.placa_veiculo}}</td></tr>
        <th>km:</th><td>{{ obj.km}}</td></tr>
        <th>Tara:</th><td>{{ obj.tara}}</td></tr>
        </table>
      </div>
      <div class="card-footer bg-transparent border-success">{{ obj.data}}</div>
    </div>
    

  </tr>
{% empty %}
  <li>Não há itens na tabela!</li>
{% endfor %}
    </tbody>

  </table>
</ul>
{% include "includes/pagination.html" %}
</div>

{% endblock content %}

{% block js %}

{% endblock js %}

administrativo/templates/lista_cargas.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% load bootstrap %}
{% block css %}
{% endblock css %}

{% block content %}

<nav class="navbar" style="background-color: #e3f2fd;">
  <h1>MVHS informações</h1>
</nav>
<div class='container text-center p-2 text-primary-emphasis bg-danger-subtle border border-primary-subtle  rounded-3'>


<nav class="navbar bg-body-tertiary">
  <div class="container-fluid">
    {% if user.is_authenticated %}
    <a class="button_adm" href="{% url 'administrativo:formulario_cargas' %}">Proxíma Carga</a>
    {% endif %}
  </div>
  <br>
  <br>
  <br>
  <br>
  <div class="container-fluid">
    <a class="button_adm" href="/">Retornar</a>
  </div>
</nav>

<h1 class='text-center'>Lista de Cargas</h1>


  {% for Cargas in object_list %}

  <tr>
    <div class="card text-bg-secondary mb-3" style="max-width: 22rem;">
      <div class="card-header bg-transparent border-success text-success"><h4>{{ Cargas.Carga_Placa}}</h4></div>
      <div class="card-body ">
        <table class="table table-success table-striped">
       <tr>
        <th>p2:</th><td>{{ Cargas.p2}}</td> 
        <th>p5:</th><td>{{ Cargas.p5}}</td>
        <th>p8:</th><td>{{ Cargas.p8}}</td></tr>
        <tr>
        <th>p13:</th><td>{{ Cargas.p13}}</td> 
        <th>p20:</th><td>{{ Cargas.p20}}</td>
        <th>p45:</th><td>{{ Cargas.p45}}</td></tr>
        

        <p>Cor :{{ Cargas.cor}}</p>
        </table>
      </div>
      <div class="card-footer bg-transparent border-success">{{ Cargas.data}}</div>
    </div>
    

  </tr>
{% empty %}
  <li>Não há itens na tabela!</li>
{% endfor %}
    </tbody>

  </table>
</ul>
{% include "includes/pagination.html" %}
</div>

{% endblock content %}

{% block js %}

{% endblock js %}

administrativo/templates/lista_motorista.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% load bootstrap %}
{% block css %}
{% endblock css %}

{% block content %}
<nav class="navbar" style="background-color: #e3f2fd;">
  MVHS informações
</nav>
<div class='container text-center p-2 text-primary-emphasis bg-danger-subtle border border-primary-subtle  rounded-3'>


<nav class="navbar bg-body-tertiary">
  <div class="container-fluid">
    <a class="button_adm" href="/">Retornar</a>
  </div>
</nav>

<h1 class='text-center'>Lista de Motoristas</h1>
<ul>


  {% for obj in object_list %}

  <tr>
    <div class="card text-bg-secondary mb-3" style="max-width: 22rem;">
      <div class="card-header bg-transparent border-success text-success"><h4>{{ obj.motorista}}</h4></div>
      <div class="card-body ">
        <table class="table table-success table-striped">
       <tr>
        <th>Data:</th><td>{{ obj.data}}</td></tr>
        
        
        </table>
      </div>
  
    </div>
    

  </tr>
{% empty %}
  <li>Não há itens na tabela!</li>
{% endfor %}
    </tbody>

  </table>
</ul>
{% include "includes/pagination.html" %}
</div>

{% endblock content %}

{% block js %}

{% endblock js %}

administrativo/templates/pes_imprimir.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% load bootstrap %}
{% block css %}

  <style>
    .form-control {
      margin: 10px;
    }
  </style>


{% endblock css %}

{% block content %}
<nav class="navbar" style="background-color: #e3f2fd;">
  MVHS informações
   <p><a class="button_adm" type='button'href="/">Retornar</a></p>
</nav>
<br>
<div class='container text-center p-2 text-primary-emphasis bg-danger-subtle border border-primary-subtle  rounded-3'>
  <form method="GET">
      <div class="container">
        <h1>Imprimir tablela de dados entre datas</h1>
        <div class="input-group">
            <div class="container">
            <span class="input-group-text" id="basic-addon1" style="display:ruby-text ;">Data inicial</span>    
            <input class="form-control "aria-describedby="basic-addon1" name="d1" type="date" ><br>
            </div>
            <div class="container">
            <span class="input-group-text" id="basic-addon2" style="display:ruby-text ;">Data final</span>
            <input class="form-control " aria-describedby="basic-addon2"name="d2" type="date" ><br>
            </div>
        </div>
          <br>
          <div class="conteiner">
            <button class="button_frota" type="submit">{{acao}}</button>
        </div>
       </div>
      </div>

    </form>

<ul>



</div>
{% endblock content %}

{% block js %}

{% endblock js %}